Replace ping with curl for internet connectivity checks in setup.sh, start_cage, and start_chromium scripts

diff --git a/start_cage b/start_cage
--- a/start_cage
+++ b/start_cage
@@ -10,9 +10,10 @@ MAX_TRIES=10
 echo "After the internet become connected, the USB ports and Ethernet ports will be disabled..."
 
 echo "Ensuring ssh is enabled..."
-sudo systemctl enable --now ssh || { echo "Failed on initialization of SSH. Exiting..."; exit 1; }
+sudo systemctl enable --now ssh \
+|| { echo "Failed on initialization of SSH. Exiting..."; exit 1; }
 
-until ping google.com -c 4 > /dev/null 2>&1; do
+until curl -I https://google.com > /dev/null 2>&1; do
     echo "Not connected on internet. Sleeping for 2 seconds..."
     sleep 2
 done
diff --git a/start_chromium b/start_chromium
--- a/start_chromium
+++ b/start_chromium
@@ -16,9 +16,9 @@ if ! [[ "$numeric_part" =~ ^[0-9]+$ ]]; then
 fi
 
 url="https://ooh.tvsimbrasil.com.br/ooh/current-ads?id=$numeric_part"
-
+base="https://ooh.tvsimbrasil.com.br"
 sleep 5s
-until ping $url -c 4 > /dev/null 2>&1; do
+until curl -I $base -c 4 > /dev/null 2>&1; do
     echo "The $url is not available. Sleeping for 20 seconds..."
     sleep 20
 done
@@ -45,4 +45,5 @@ chromium --kiosk $url \
         --disable-domain-reliability \
         --safebrowsing-disable-auto-update \
         --disable-client-side-phishing-detection \
-        --metrics-recording-only || { echo "Failed on initialization of chromium. Exiting..."; exit 1; }
+        --metrics-recording-only \
+        || { echo "Failed on initialization of chromium. Exiting..."; exit 1; }
